layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name
      - designPatterns
      - Memory-Allocator
      - dcCoder9.github.io
      - Polygon-ScanLine-Conversion-Clipping

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: wesley.moncrief
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: wesley-moncrief-80b24a97/
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: The unit testing pyramid vs the testing trophy
    web_url: https://github.com/topics/csshttps://kentcdodds.com/blog/write-tests
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Design patterns
    web_url: https://www.pluralsight.com/courses/design-patterns-structural-playbook
    image_url: https://i.udemycdn.com/course/750x422/1388684_4c5f_2.jpg

  - name: Board games!
    image_url: https://store.greaterthangames.com/images/product/Spirit%20Island%20components.png
